# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
