# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_fileupload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='source',
            field=models.CharField(choices=[('Adwords', 'Adwords'), ('Taboola', 'Taboola'), ('Outbrain', 'Outbrain'), ('Times-Internet', 'Times-Internet')], default='Adwords', max_length=100),
        ),
    ]
