# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_fileupload_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('taboola', 'Taboola'), ('adwords', 'AdWords'), ('timesinternet', 'Times-Internet'), ('outbrain', 'Outbrain')], default='Adwords', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
