# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20170612_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('timesinternet', 'Times-Internet'), ('adwords', 'AdWords'), ('taboola', 'Taboola'), ('outbrain', 'Outbrain')], default='Adwords', max_length=100),
        ),
    ]
