# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_auto_20170612_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('adwords', 'AdWords'), ('taboola', 'Taboola'), ('timesinternet', 'Times Internet'), ('outbrain', 'Outbrain')], default='adwords', max_length=100),
        ),
    ]
