# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_auto_20170612_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.CharField(choices=[('adwords', 'AdWords'), ('outbrain', 'Outbrain'), ('timesinternet', 'Times Internet'), ('taboola', 'Taboola')], default='adwords', max_length=100),
        ),
    ]
